spring:
  application:
    name: java-pro-spring
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    show-sql: true
  data:
    jdbc:
      dialect: postgresql

integrations:
  clients-info-service:
    url: "http://localhost:8190/api/v1/clients"
  limits-info-service:
    url: "http://localhost:8192/api/v1/limits"